version: "3"
services:
  database:
    build: ./database
    container_name: database-container
    # restart: 'on-failure'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    networks:
      - default
    # ports:
    #   - 3306:3306

  brocker:
    image: webcenter/activemq:latest
    container_name: activemq-broker-container
    networks:
      - default
    ports:
      - 8161:8161
      # - 61616:61616
      # - 61613:61613

  spring-app-game:
    build: ./monolithic
    # volumes :
    #   - build:/usr/src/app
    container_name: spring-container
    environment:
      SERVER_IP: spring-container
      SERVER_PORT: 8082
      DATABASE_USER: admin
      DATABASE_PWD: admin
      DATABASE_HOST: database-container
      DATABASE_PORT: 3306
      DATABASE_NAME: main
      BROCKER_HOST: activemq-broker-container
      BROCKER_PORT: 61616
      BROCKER_USER: admin
      BROCKER_PWD: admin
      MQ_IN: "com.cpe.springboot.logs.in"
    networks:
      - default
    depends_on:
      - brocker
      - database
    # ports:
    # - 8082:8082

  ngnix-reverse-proxy:
    build: ./reverse-proxy
    container_name: reverse-proxy-container
    networks:
      - default
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 3001:3001
    depends_on:
      - ngnix-static-server
      - spring-app-game
      - log-service

  ngnix-static-server:
    build: ./static-server
    container_name: "static-server-container"
    volumes:
      - ./static-server/resources:/etc/nginx/html
    networks:
      - default
    # ports:
    #   - 8080:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-container"
    environment:
      PMA_HOST: database-container
      PMA_PORT: 3306
    networks:
      - default
    ports:
      - 8081:80
    depends_on:
      - database

  log-service:
    build: ./log-service
    container_name: log-service-container
    environment:
      MQ_IN: "com.cpe.springboot.logs.in"
      SERVER_IP: log-service-container
      SERVER_PORT: 8083
      DATABASE_USER: admin
      DATABASE_PWD: admin
      DATABASE_HOST: database-container
      DATABASE_PORT: 3306
      DATABASE_NAME: main
      BROCKER_HOST: activemq-broker-container
      BROCKER_PORT: 61616
      BROCKER_USER: admin
      BROCKER_PWD: admin
    networks:
      - default
    depends_on:
      - brocker
      - database
    # ports:
    #   - 8082:8082

  game-server:
    build: ./game-server
    container_name: game-server-container
    environment:
      SERVER_PORT: 8085
      BROCKER_HOST: activemq-broker-container
      BROCKER_PORT: 61613
      BROCKER_USER: admin
      BROCKER_PWD: admin
      MQ_OUT_LOGS: 'com.cpe.springboot.logs.in'
    ports: 
      - 8085:8085
    networks:
      - default
    depends_on:
      - brocker

networks:
  default:
    driver: bridge
